### ISSUE TITLE
Not really an issue, but couldn't find a discussions section - can it support GPU?

### ISSUE THREAD

**Issue by babanovac1980** [stephengpope/no-code-architects-toolkit#84]
I am using this awesome project and I cannot complain about anything. Works nicely.
However, at least for the captions endpoint it's hammering my CPUs and I'd prefer offloading to the GPU if possible.

![Image](https://github.com/user-attachments/assets/e1033cc6-d2aa-4eaa-b125-be31670b5ed0)

**Comment by stephengpope** [comment]
it should be able to, I think we just need to compile in the settings to include support, I'll take a look.

**Comment by BenjaminKeating1986** [comment]
This would be an amazing feature, i have this setup on a dedicated server so it not needing a GPU is nice but i also have it setup on my pc that does have a decent GPU would be great if this could be added as an environmental variable to use GPU

**Comment by MPetrovsky** [comment]
@BenjaminKeating1986 Hey, I just spent a few hours on this.
Everything is working fine with this repo — the only thing you need for GPU support is to install the [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-the-nvidia-container-toolkit) by following the official guide, and then run the container with:


`docker run -d **--gpus all** ...`

**Comment by Tobe2d** [comment]
I found this amazing repo from @BenjaminKeating1986 video on YouTube, huge thanks to him for highlighting it! 🙏 And big shoutout to @stephengpope for creating this powerful toolkit 👏

While setting things up, I wanted to enable GPU support and thought I'd share the working solution here for anyone else looking to do the same. You just need to add a deploy section in your Docker Compose file like this:



```
services:
  nca-toolkit:
    image: stephengpope/no-code-architects-toolkit:latest
    container_name: nca-toolkit
    ports:
      - "8080:8080"  
    environment:
      API_KEY: #anything_works
      S3_ENDPOINT_URL:  #YOUR--->S3_ENDPOINT_URL
      S3_ACCESS_KEY: #YOUR--->S3_ACCESS_KEY
      S3_SECRET_KEY: #YOUR--->S3_SECRET_KEY
      S3_BUCKET_NAME: #YOUR--->S3_BUCKET_NAME
      S3_REGION: None
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
```

This enabled the container to access my GPU properly using Docker Compose NVIDIA Container Toolkit.


I always prefer to use Docker Compose over docker run since it allows better management and integration with other containers.

Hope it helps someone else too!
